/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sekwah.mira4j;

import org.junit.Test;
import static org.junit.Assert.*;

public class Mira4JTest {
    @Test public void testAppHasAGreeting() {
        Mira4J classUnderTest = new Mira4J();
        assertNotNull("App exists. Maybe look at doing some proper unit tests a some point ;)", classUnderTest);
    }
}
